# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/PacMan.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'
  wixSolution: '**/PacMan-setup.sln'
  executablePublishPath: '$(Build.ArtifactStagingDirectory)/executable/'
  istallerPublishPath: '$(Build.ArtifactStagingDirectory)/installer/'

steps:
- script: |
    vcpkg integrate install
    vcpkg install sdl2 sdl2-image
  displayName: vcpkg

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/$(buildConfiguration)/'
    Contents: '**/*.[(exe)(dll)]'
    TargetFolder: '$(executablePublishPath)'
    
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'Executable'
    targetPath: '$(executablePublishPath)'

- task: VSBuild@1
  inputs:
    solution: '$(wixSolution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/PacMan-setup/bin/$(buildConfiguration)/'
    Contents: '**/*.msi'
    TargetFolder: '$(installerPublishPath)'
    
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'Installer'
    targetPath: '$(installerPublishPath)'
