trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  coverageDownloadLocation: '$(Build.SourcesDirectory)\DownloadedCoverage'
  coverageOutputLocation: '$(Build.SourcesDirectory)\TestResults'
  toolsLocation: '$(Build.SourcesDirectory)\tools'

steps:
- task: CmdLine@2
  displayName: Create output directory.
  inputs:
    script: 'mkdir $(coverageOutputLocation)'

- task: DownloadPipelineArtifact@2
  displayName: Download .coverage artifacts
  inputs:
    buildType: 'specific'
    project: '41987b1d-47e2-4fea-90ac-c2b42d11a558'
    definition: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    artifactName: 'convertedCoverage'
    itemPattern: '**/*.coverage'
    targetPath: '$(coverageDownloadLocation)'

- task: UsePythonVersion@0
  displayName: Set up python version.
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: PythonScript@0
  displayName: Convert .coverage files to .xml
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(toolsLocation)/convert_coverage.py'
    arguments: '$(coverageDownloadLocation)'
    workingDirectory: '$(coverageOutputLocation)'

- task: PublishPipelineArtifact@0
  displayName: Publish .xml files
  inputs:
    artifactName: 'convertedCoverage'
    targetPath: '$(coverageOutputLocation)'
