trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  coverageDownloadLocation: '$(Build.SourcesDirectory)/DownloadedCoverage'
  convertedOutputLocation: '$(Build.SourcesDirectory)/TestResults'
  toolsLocation: '$(Build.SourcesDirectory)/tools'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '41987b1d-47e2-4fea-90ac-c2b42d11a558'
    definition: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    artifactName: 'convertedCoverage'
    itemPattern: '**/*.coverage'
    targetPath: '$(coverageDownloadLocation)'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: CmdLine@2
  inputs:
    script: 'mkdir $(coverageOutputLocation)'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(toolsLocation)/convert_coverage.py'
    arguments: '$(coverageDownloadLocation)'
    workingDirectory: '$(coverageOutputLocation)'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'convertedCoverage'
    targetPath: '$(convertedOutputLocation)'
