# SonarCloud pipeline for the PacMan.
trigger: none

schedules:
- cron: "0 0,6,9,12,15,18,21 * * *"
  displayName: Scheduled SonarCloud Build
  branches:
    include:
    - master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '$(Build.SourcesDirectory)/PacMan.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Debug'
  buildWrapperOutputDir: '$(Build.SourcesDirectory)/build_wrapper_output_directory'
  buildWrapperExe: '$(Build.SourcesDirectory)/tools/build-wrapper-win-x86-64.exe'
  msBuildExe: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
  toolsLocation: '$(Build.SourcesDirectory)\tools'
  codeCoverageLocationRunsettings: '$(Build.SourcesDirectory)/code_coverage_loc.runsettings'
  codeCoverageOutput: $(Build.SourcesDirectory)\TestResults'
  coverageOutputLocation: '$(Build.SourcesDirectory)\CoverageResults'
  coverageFiles: '$(coverageOutputLocation)\*.xml'

steps:
- script: |
    vcpkg install sdl2 sdl2-image gtest
    vcpkg integrate install
  displayName: vcpkg

- task: NuGetToolInstaller@0
  displayName: 'Nuget - Install'

- task: NuGetCommand@2
  displayName: 'Nuget - Restore Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  displayName: 'SonarCloud - Prepare'
  inputs:
    SonarCloud: 'PacManSonarCloud'
    organization: 'beardedplatypus'
    scannerMode: 'MSBuild'
    projectKey: 'BeardedPlatypus_PacMan'
    projectName: 'PacMan'
    extraProperties: |
      sonar.cfamily.build-wrapper-output=$(buildWrapperOutputDir)
      sonar.cfamily.vscoveragexml.reportsPath=$(coverageFiles)

- task: PowerShell@2
  displayName: MSBuild
  inputs:
    targetType: 'inline'
    script: '& $(buildWrapperExe) --out-dir $(buildWrapperOutputDir) "$(msBuildExe)" $(solution) -nologo -p:Configuration=$(buildConfiguration) -p:Platform=$(buildPlatform)'

- task: UsePythonVersion@0
  displayName: Set up python version.
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(toolsLocation)/location_runsettings.py'
    arguments: '$(codeCoverageLocationRunsettings) $(codeCoverageOutput)'

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Test - Install'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: VSTest@2
  displayName: 'Test - Run'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
      **\$(buildConfiguration)\*.Test.exe
      !**\*TestAdapter.dll
      !**\obj\**
      !**\$(buildConfiguration)\gmock.dll
      !**\$(buildConfiguration)\libpng16.dll
      !**\$(buildConfiguration)\SDL2.dll
      !**\$(buildConfiguration)\SDL2_image.dll
      !**\$(buildConfiguration)\zlib1.dll
    codeCoverageEnabled: true
    runSettingsFile: '$(codeCoverageLocationRunsettings)'

- task: CmdLine@2
  displayName: Coverage - Create .coverage output directory.
  inputs:
    script: 'mkdir $(coverageOutputLocation)'

- task: PythonScript@0
  displayName: Coverage - Convert .coverage files to .xml
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(toolsLocation)/convert_coverage.py'
    arguments: '$(codeCoverageOutput)'
    workingDirectory: '$(coverageOutputLocation)'

- task: PublishPipelineArtifact@0
  displayName: Coverage - Publish .xml files
  inputs:
    artifactName: 'convertedCoverage'
    targetPath: '$(coverageOutputLocation)'

- task: SonarCloudAnalyze@1
  displayName: 'SonarCloud - Analyze'

- task: SonarCloudPublish@1
  displayName: 'SonarCloud - Publish'
  inputs:
    pollingTimeoutSec: '300'
