# SonarCloud pipeline for the PacMan.
trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '$(Build.SourcesDirectory)/PacMan.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'
  buildWrapperOutputDir: '$(Build.SourcesDirectory)/build_wrapper_output_directory'
  buildWrapperExe: '$(Build.SourcesDirectory)/tools/build-wrapper-win-x86-64.exe'
  msBuildExe: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
  codeCoverageExe: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Dynamic Code Coverage Tools\codecoverage.exe'
  coverageFile: '**/TestResults/**/*.coverage'
  testResults: '$(Agent.TempDirectory)/TestResults'
  outputCoverageXML: '$(Build.SourcesDirectory)/codeCoverage.xml'

steps:
- script: |
    vcpkg install sdl2 sdl2-image gtest
    vcpkg integrate install
  displayName: vcpkg

- task: NuGetToolInstaller@0
  displayName: 'Nuget - Install'

- task: NuGetCommand@2
  displayName: 'Nuget - Restore Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  displayName: 'SonarCloud - Prepare'
  inputs:
    SonarCloud: 'PacManSonarCloud'
    organization: 'beardedplatypus'
    scannerMode: 'MSBuild'
    projectKey: 'BeardedPlatypus_PacMan'
    projectName: 'PacMan'
    extraProperties: |
      'sonar.cfamily.build-wrapper-output=$(buildWrapperOutputDir)'
      'sonar.cfamily.vscoveragexml.reportsPath=$(outputCoverageXML)'

- task: PowerShell@2
  displayName: MSBuild
  inputs:
    targetType: 'inline'
    script: '& $(buildWrapperExe) --out-dir $(buildWrapperOutputDir) "$(msBuildExe)" $(solution) -nologo -p:Configuration=$(buildConfiguration) -p:Platform=$(buildPlatform)'

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Test - Install'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: VSTest@2
  displayName: 'Test - Run'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
      **\$(buildConfiguration)\*.Test.exe
      !**\*TestAdapter.dll
      !**\obj\**
      !**\$(buildConfiguration)\gmock.dll
      !**\$(buildConfiguration)\libpng16.dll
      !**\$(buildConfiguration)\SDL2.dll
      !**\$(buildConfiguration)\SDL2_image.dll
      !**\$(buildConfiguration)\zlib1.dll
    codeCoverageEnabled: true

- task: CopyFiles@2
  displayName: 'Code Coverage - Copy .coverage files'
  inputs:
    SourceFolder: '$(testResults)'
    Contents: '**/*.coverage'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    
- task: PublishPipelineArtifact@0
  displayName: 'Code Coverage - Publish .coverage files'
  inputs:
    artifactName: 'BuildWrapperOutput'
    targetPath: '$(Build.ArtifactStagingDirectory)'

- task: PowerShell@2
  displayName: 'Test - Convert code coverage to xml'
  inputs:
    targetType: 'inline'
    script: '& "$(codeCoverageExe)" analyze /output:$(outputCoverageXML) $(coverageFile)'

- task: SonarCloudAnalyze@1
  displayName: 'SonarCloud - Analyze'

- task: SonarCloudPublish@1
  displayName: 'SonarCloud - Publish'
  inputs:
    pollingTimeoutSec: '300'
