trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/PacMan.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'
  buildWrapperOutputDir: 'build_wrapper_output_directory'
  buildWrapperExe: '$(Build.Repository.LocalPath)\tools\build-wrapper-win-x86-64.exe'

steps:
- script: |
    '$(buildWrapperExe)'
  displayName: SonarCloud - Verify build-wrapper

- script: |
    vcpkg install sdl2 sdl2-image gtest
    vcpkg integrate install
  displayName: vcpkg

- task: NuGetToolInstaller@0
  displayName: 'Nuget - Install'

- task: NuGetCommand@2
  displayName: 'Nuget - Restore Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  displayName: 'SonarCloud - Prepare'
  inputs:
    SonarCloud: 'PacManSonarCloud'
    organization: 'beardedplatypus'
    scannerMode: 'MSBuild'
    projectKey: 'BeardedPlatypus_PacMan'
    projectName: 'PacMan'
    extraProperties: |
      'sonar.cfamily.build-wrapper-output=$(buildWrapperOutputDir)'

- task: CmdLine@2
  inputs:
    script: |
      '$(buildWrapperExe)' --out-dir '$(buildWrapperOutputDir)' 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' PacMan.sln -nologo -p:Configuration='$(buildConfiguration)' -p:Platform='$(buildPlatform)'

- task: SonarCloudAnalyze@1
  displayName: 'SonarCloud - Analyze'

- task: SonarCloudPublish@1
  displayName: 'SonarCloud - Publish'
  inputs:
    pollingTimeoutSec: '300'
